{"level":"ERROR","location":"[get_call:118] fyersModel","message":"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","timestamp":"2024-01-16 21:01:05,648+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[get_call:118] fyersModel","message":"('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))","timestamp":"2024-01-16 21:02:39,995+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[get_call:118] fyersModel","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AABBOTINDIA-EQ&resolution=D&date_format=1&range_from=2023-08-08&range_to=2024-01-17&cont_flag=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001ECF79E0190>, 'Connection to api-t1.fyers.in timed out. (connect timeout=None)'))","timestamp":"2024-01-17 20:13:51,371+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[get_call:118] fyersModel","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AABBOTINDIA-EQ&resolution=D&date_format=1&range_from=2023-08-09&range_to=2024-01-18&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000022C81FA0550>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))","timestamp":"2024-01-18 10:23:40,753+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[get_call:118] fyersModel","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AABBOTINDIA-EQ&resolution=D&date_format=1&range_from=2023-08-09&range_to=2024-01-18&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000019C0CF391D0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))","timestamp":"2024-01-18 12:11:37,596+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[get_call:118] fyersModel","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AABBOTINDIA-EQ&resolution=D&date_format=1&range_from=2023-08-09&range_to=2024-01-18&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000273E49354D0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))","timestamp":"2024-01-18 12:11:50,395+0530","service":"FyersDataSocket"}
